# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CVEPdummyScript.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'CVEPdummyScript.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x43VEPdummyScript.proto\x1a\x1bgoogle/protobuf/empty.proto\":\n\x11\x61\x64\x64SeqDataRequest\x12\x13\n\x0bsequenceNum\x18\x01 \x01(\x05\x12\x10\n\x08\x44uration\x18\x02 \x01(\x02\"\'\n\x14\x64\x65\x63odeChoiceResponse\x12\x0f\n\x07message\x18\x01 \x01(\x05\"(\n\x15trainingModelResponse\x12\x0f\n\x07message\x18\x01 \x01(\x05\x32\xcb\x01\n\x0f\x43VEPdummyScript\x12\x38\n\naddSeqData\x12\x12.addSeqDataRequest\x1a\x16.google.protobuf.Empty\x12=\n\x0c\x64\x65\x63odeChoice\x12\x16.google.protobuf.Empty\x1a\x15.decodeChoiceResponse\x12?\n\rtrainingModel\x12\x16.google.protobuf.Empty\x1a\x16.trainingModelResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CVEPdummyScript_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDSEQDATAREQUEST']._serialized_start=54
  _globals['_ADDSEQDATAREQUEST']._serialized_end=112
  _globals['_DECODECHOICERESPONSE']._serialized_start=114
  _globals['_DECODECHOICERESPONSE']._serialized_end=153
  _globals['_TRAININGMODELRESPONSE']._serialized_start=155
  _globals['_TRAININGMODELRESPONSE']._serialized_end=195
  _globals['_CVEPDUMMYSCRIPT']._serialized_start=198
  _globals['_CVEPDUMMYSCRIPT']._serialized_end=401
# @@protoc_insertion_point(module_scope)
