# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CVEP_TEST3.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'CVEP_TEST3.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x43VEP_TEST3.proto\x1a\x1bgoogle/protobuf/empty.proto\"=\n\x13\x61\x64\x64_seq_dataRequest\x12\x14\n\x0csequence_num\x18\x01 \x01(\x05\x12\x10\n\x08\x64uration\x18\x02 \x01(\x02\"!\n\x0e\x64\x65\x63odeResponse\x12\x0f\n\x07message\x18\x01 \x01(\x05\"#\n\x10trainingResponse\x12\x0f\n\x07message\x18\x01 \x01(\x05\x32\xb6\x01\n\x0cNeuralCooked\x12<\n\x0c\x61\x64\x64_seq_data\x12\x14.add_seq_dataRequest\x1a\x16.google.protobuf.Empty\x12\x31\n\x06\x64\x65\x63ode\x12\x16.google.protobuf.Empty\x1a\x0f.decodeResponse\x12\x35\n\x08training\x12\x16.google.protobuf.Empty\x1a\x11.trainingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CVEP_TEST3_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADD_SEQ_DATAREQUEST']._serialized_start=49
  _globals['_ADD_SEQ_DATAREQUEST']._serialized_end=110
  _globals['_DECODERESPONSE']._serialized_start=112
  _globals['_DECODERESPONSE']._serialized_end=145
  _globals['_TRAININGRESPONSE']._serialized_start=147
  _globals['_TRAININGRESPONSE']._serialized_end=182
  _globals['_NEURALCOOKED']._serialized_start=185
  _globals['_NEURALCOOKED']._serialized_end=367
# @@protoc_insertion_point(module_scope)
