# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import CVEPdummyScript_pb2 as CVEPdummyScript__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in CVEPdummyScript_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CVEPdummyScriptStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.addSeqData = channel.unary_unary(
                '/CVEPdummyScript/addSeqData',
                request_serializer=CVEPdummyScript__pb2.addSeqDataRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.decodeChoice = channel.unary_unary(
                '/CVEPdummyScript/decodeChoice',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=CVEPdummyScript__pb2.decodeChoiceResponse.FromString,
                _registered_method=True)
        self.trainingModel = channel.unary_unary(
                '/CVEPdummyScript/trainingModel',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=CVEPdummyScript__pb2.trainingModelResponse.FromString,
                _registered_method=True)


class CVEPdummyScriptServicer(object):
    """Missing associated documentation comment in .proto file."""

    def addSeqData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def decodeChoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def trainingModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CVEPdummyScriptServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'addSeqData': grpc.unary_unary_rpc_method_handler(
                    servicer.addSeqData,
                    request_deserializer=CVEPdummyScript__pb2.addSeqDataRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'decodeChoice': grpc.unary_unary_rpc_method_handler(
                    servicer.decodeChoice,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=CVEPdummyScript__pb2.decodeChoiceResponse.SerializeToString,
            ),
            'trainingModel': grpc.unary_unary_rpc_method_handler(
                    servicer.trainingModel,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=CVEPdummyScript__pb2.trainingModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CVEPdummyScript', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CVEPdummyScript', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CVEPdummyScript(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def addSeqData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CVEPdummyScript/addSeqData',
            CVEPdummyScript__pb2.addSeqDataRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def decodeChoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CVEPdummyScript/decodeChoice',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            CVEPdummyScript__pb2.decodeChoiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def trainingModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CVEPdummyScript/trainingModel',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            CVEPdummyScript__pb2.trainingModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
