from utils.general import slice_len_for

REFRESH_INTERVAL = 4
INFERENCE_REFRESH_INTERVAL = 200



OPENBCI_EEG_CHANNEL_SIZE = 31
OPENBCI_EEG_USEFUL_CHANNELS = slice(1, 17)
OPENBCI_EEG_SAMPLING_RATE = 125.
OPENBCI_EEG_USEFUL_CHANNELS_NUM = slice_len_for(OPENBCI_EEG_USEFUL_CHANNELS, OPENBCI_EEG_CHANNEL_SIZE)

UNITY_LSL_CHANNEL_SIZE = 17
UNITY_LSL_SAMPLING_RATE = 70.
UNITY_LSL_USEFUL_CHANNELS = slice(1, 10)
UNITY_LSL_USEFUL_CHANNELS_NUM = slice_len_for(UNITY_LSL_USEFUL_CHANNELS, UNITY_LSL_CHANNEL_SIZE)

EYE_INFERENCE_WINDOW_SEC = 4
EYE_INFERENCE_SIZE_MULTIPLIER = 2
EYE_WINDOW_STRIDE_SEC = 0.2 # unit is in seconds

EYE_WINDOW_STRIDE_TIMESTEMPS = int(UNITY_LSL_SAMPLING_RATE * EYE_WINDOW_STRIDE_SEC)
EYE_INFERENCE_TIMESTEPS = int(UNITY_LSL_SAMPLING_RATE * EYE_INFERENCE_WINDOW_SEC)
EYE_INFERENCE_SEND_SIZE = int(EYE_INFERENCE_TIMESTEPS * EYE_INFERENCE_SIZE_MULTIPLIER)

PLOT_RETAIN_HISTORY = 10.  # retain 10 seconds of history
