# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: HelloWorldRPCExample.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'HelloWorldRPCExample.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aHelloWorldRPCExample.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1f\n\x0fSayHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\x10SayHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2@\n\rHelloWorldRPC\x12/\n\x08SayHello\x12\x10.SayHelloRequest\x1a\x11.SayHelloResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HelloWorldRPCExample_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SAYHELLOREQUEST']._serialized_start=59
  _globals['_SAYHELLOREQUEST']._serialized_end=90
  _globals['_SAYHELLORESPONSE']._serialized_start=92
  _globals['_SAYHELLORESPONSE']._serialized_end=127
  _globals['_HELLOWORLDRPC']._serialized_start=129
  _globals['_HELLOWORLDRPC']._serialized_end=193
# @@protoc_insertion_point(module_scope)
