# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AsyncRPCExample.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x41syncRPCExample.proto\x1a\x1bgoogle/protobuf/empty.proto\"-\n\x1b\x41syncOneArgOneReturnRequest\x12\x0e\n\x06input0\x18\x01 \x01(\t\"/\n\x1c\x41syncOneArgOneReturnResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2f\n\x0f\x41syncRPCExample\x12S\n\x14\x41syncOneArgOneReturn\x12\x1c.AsyncOneArgOneReturnRequest\x1a\x1d.AsyncOneArgOneReturnResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AsyncRPCExample_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASYNCONEARGONERETURNREQUEST']._serialized_start=54
  _globals['_ASYNCONEARGONERETURNREQUEST']._serialized_end=99
  _globals['_ASYNCONEARGONERETURNRESPONSE']._serialized_start=101
  _globals['_ASYNCONEARGONERETURNRESPONSE']._serialized_end=148
  _globals['_ASYNCRPCEXAMPLE']._serialized_start=150
  _globals['_ASYNCRPCEXAMPLE']._serialized_end=252
# @@protoc_insertion_point(module_scope)
