# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import vision_pb2 as vision__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in vision_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VisionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessWingmanCamera = channel.unary_unary(
                '/vision.Vision/ProcessWingmanCamera',
                request_serializer=vision__pb2.ProcessWingmanCameraRequest.SerializeToString,
                response_deserializer=vision__pb2.ProcessWingmanCameraReply.FromString,
                _registered_method=True)
        self.ProcessFixationCamera = channel.unary_unary(
                '/vision.Vision/ProcessFixationCamera',
                request_serializer=vision__pb2.ProcessFixationCameraRequest.SerializeToString,
                response_deserializer=vision__pb2.ProcessFixationCameraReply.FromString,
                _registered_method=True)
        self.OnBlockStart = channel.unary_unary(
                '/vision.Vision/OnBlockStart',
                request_serializer=vision__pb2.OnBlockStartRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GazeFrame = channel.unary_unary(
                '/vision.Vision/GazeFrame',
                request_serializer=vision__pb2.GazeFrameRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.LabelTarget = channel.unary_unary(
                '/vision.Vision/LabelTarget',
                request_serializer=vision__pb2.LabelTargetRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class VisionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessWingmanCamera(self, request, context):
        """1) Analyze Wingman images/metadata -> dict: ID-> confidence level
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessFixationCamera(self, request, context):
        """2) Analyze Fixation images/metadata -> dict: ID-> confidence level
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnBlockStart(self, request, context):
        """3) Fire-and-forget integer push (no return body)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GazeFrame(self, request, context):
        """4) Fire-and-forget gaze frame (no return body)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LabelTarget(self, request, context):
        """5) Fire-and-forget label target (no return body)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VisionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessWingmanCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessWingmanCamera,
                    request_deserializer=vision__pb2.ProcessWingmanCameraRequest.FromString,
                    response_serializer=vision__pb2.ProcessWingmanCameraReply.SerializeToString,
            ),
            'ProcessFixationCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessFixationCamera,
                    request_deserializer=vision__pb2.ProcessFixationCameraRequest.FromString,
                    response_serializer=vision__pb2.ProcessFixationCameraReply.SerializeToString,
            ),
            'OnBlockStart': grpc.unary_unary_rpc_method_handler(
                    servicer.OnBlockStart,
                    request_deserializer=vision__pb2.OnBlockStartRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GazeFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.GazeFrame,
                    request_deserializer=vision__pb2.GazeFrameRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'LabelTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.LabelTarget,
                    request_deserializer=vision__pb2.LabelTargetRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vision.Vision', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vision.Vision', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Vision(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessWingmanCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vision.Vision/ProcessWingmanCamera',
            vision__pb2.ProcessWingmanCameraRequest.SerializeToString,
            vision__pb2.ProcessWingmanCameraReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessFixationCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vision.Vision/ProcessFixationCamera',
            vision__pb2.ProcessFixationCameraRequest.SerializeToString,
            vision__pb2.ProcessFixationCameraReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnBlockStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vision.Vision/OnBlockStart',
            vision__pb2.OnBlockStartRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GazeFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vision.Vision/GazeFrame',
            vision__pb2.GazeFrameRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LabelTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vision.Vision/LabelTarget',
            vision__pb2.LabelTargetRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
