# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vision.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'vision.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvision.proto\x12\x06vision\x1a\x1bgoogle/protobuf/empty.proto\"\xa7\x01\n\x0e\x41nalyzeRequest\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\x01\x12\x13\n\x0b\x63olor_image\x18\x02 \x01(\x0c\x12\x13\n\x0b\x64\x65pth_image\x18\x03 \x01(\x0c\x12\x11\n\tbbox_json\x18\x04 \x01(\t\x12\x1b\n\x13gaze_item_index_dtn\x18\x05 \x01(\x0c\x12%\n\x1d\x63urrent_screen_location_bytes\x18\x06 \x01(\x0c\"v\n\x0c\x41nalyzeReply\x12\x35\n\tid_scores\x18\x01 \x03(\x0b\x32\".vision.AnalyzeReply.IdScoresEntry\x1a/\n\rIdScoresEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"\x1f\n\x0ePushIntRequest\x12\r\n\x05value\x18\x01 \x01(\x05\"{\n\x10GazeFrameRequest\x12\x37\n\x08id_gazed\x18\x01 \x03(\x0b\x32%.vision.GazeFrameRequest.IdGazedEntry\x1a.\n\x0cIdGazedEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\".\n\x12LabelTargetRequest\x12\x0b\n\x03idx\x18\x01 \x01(\x05\x12\x0b\n\x03\x64tn\x18\x02 \x01(\x05\x32\x82\x02\n\x06Vision\x12\x39\n\x07\x41nalyze\x12\x16.vision.AnalyzeRequest\x1a\x14.vision.AnalyzeReply\"\x00\x12;\n\x07PushInt\x12\x16.vision.PushIntRequest\x1a\x16.google.protobuf.Empty\"\x00\x12=\n\tGazeFrame\x12\x18.vision.GazeFrameRequest\x1a\x16.google.protobuf.Empty\x12\x41\n\x0bLabelTarget\x12\x1a.vision.LabelTargetRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vision_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYZEREPLY_IDSCORESENTRY']._loaded_options = None
  _globals['_ANALYZEREPLY_IDSCORESENTRY']._serialized_options = b'8\001'
  _globals['_GAZEFRAMEREQUEST_IDGAZEDENTRY']._loaded_options = None
  _globals['_GAZEFRAMEREQUEST_IDGAZEDENTRY']._serialized_options = b'8\001'
  _globals['_ANALYZEREQUEST']._serialized_start=54
  _globals['_ANALYZEREQUEST']._serialized_end=221
  _globals['_ANALYZEREPLY']._serialized_start=223
  _globals['_ANALYZEREPLY']._serialized_end=341
  _globals['_ANALYZEREPLY_IDSCORESENTRY']._serialized_start=294
  _globals['_ANALYZEREPLY_IDSCORESENTRY']._serialized_end=341
  _globals['_PUSHINTREQUEST']._serialized_start=343
  _globals['_PUSHINTREQUEST']._serialized_end=374
  _globals['_GAZEFRAMEREQUEST']._serialized_start=376
  _globals['_GAZEFRAMEREQUEST']._serialized_end=499
  _globals['_GAZEFRAMEREQUEST_IDGAZEDENTRY']._serialized_start=453
  _globals['_GAZEFRAMEREQUEST_IDGAZEDENTRY']._serialized_end=499
  _globals['_LABELTARGETREQUEST']._serialized_start=501
  _globals['_LABELTARGETREQUEST']._serialized_end=547
  _globals['_VISION']._serialized_start=550
  _globals['_VISION']._serialized_end=808
# @@protoc_insertion_point(module_scope)
