# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VariousArgsAndReturnsRPCExample.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%VariousArgsAndReturnsRPCExample.proto\x1a\x1bgoogle/protobuf/empty.proto\"/\n\x1d\x45xampleOneArgOneReturnRequest\x12\x0e\n\x06input0\x18\x01 \x01(\t\"1\n\x1e\x45xampleOneArgOneReturnResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"(\n\x15TestRPCNoArgsResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"(\n\x16TestRPCNoReturnRequest\x12\x0e\n\x06input0\x18\x01 \x01(\x02\"?\n\x1dTestRPCTwoArgTwoReturnRequest\x12\x0e\n\x06input0\x18\x01 \x01(\t\x12\x0e\n\x06input1\x18\x02 \x01(\x05\"D\n\x1eTestRPCTwoArgTwoReturnResponse\x12\x10\n\x08message0\x18\x01 \x01(\t\x12\x10\n\x08message1\x18\x02 \x01(\x05\x32\x91\x03\n\nRPCExample\x12Y\n\x16\x45xampleOneArgOneReturn\x12\x1e.ExampleOneArgOneReturnRequest\x1a\x1f.ExampleOneArgOneReturnResponse\x12?\n\rTestRPCNoArgs\x12\x16.google.protobuf.Empty\x1a\x16.TestRPCNoArgsResponse\x12H\n\x16TestRPCNoInputNoReturn\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\x42\n\x0fTestRPCNoReturn\x12\x17.TestRPCNoReturnRequest\x1a\x16.google.protobuf.Empty\x12Y\n\x16TestRPCTwoArgTwoReturn\x12\x1e.TestRPCTwoArgTwoReturnRequest\x1a\x1f.TestRPCTwoArgTwoReturnResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'VariousArgsAndReturnsRPCExample_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXAMPLEONEARGONERETURNREQUEST']._serialized_start=70
  _globals['_EXAMPLEONEARGONERETURNREQUEST']._serialized_end=117
  _globals['_EXAMPLEONEARGONERETURNRESPONSE']._serialized_start=119
  _globals['_EXAMPLEONEARGONERETURNRESPONSE']._serialized_end=168
  _globals['_TESTRPCNOARGSRESPONSE']._serialized_start=170
  _globals['_TESTRPCNOARGSRESPONSE']._serialized_end=210
  _globals['_TESTRPCNORETURNREQUEST']._serialized_start=212
  _globals['_TESTRPCNORETURNREQUEST']._serialized_end=252
  _globals['_TESTRPCTWOARGTWORETURNREQUEST']._serialized_start=254
  _globals['_TESTRPCTWOARGTWORETURNREQUEST']._serialized_end=317
  _globals['_TESTRPCTWOARGTWORETURNRESPONSE']._serialized_start=319
  _globals['_TESTRPCTWOARGTWORETURNRESPONSE']._serialized_end=387
  _globals['_RPCEXAMPLE']._serialized_start=390
  _globals['_RPCEXAMPLE']._serialized_end=791
# @@protoc_insertion_point(module_scope)
